#!/usr/bin/env python3

import argparse
import os
import subprocess
import tempfile


SCRIPTS_DIRECTORY = os.path.dirname(os.path.abspath(__file__))
ROOT_DIRECTORY = os.path.dirname(SCRIPTS_DIRECTORY)
HTML_DIRECTORY = os.path.join(ROOT_DIRECTORY, "html")
RENDERS_DIRECTORY = os.path.join(ROOT_DIRECTORY, "renders")

HOURS = ["00", "02", "04", "06", "08", "10", "12", "14", "16", "18", "20", "22"]

DIMENSIONS = [
    (1680, 1050),
    (2560, 1600),
    (3840, 1600),
]


def generate(width, height):
    scale = 2
    output_directory = os.path.join(RENDERS_DIRECTORY, "%dx%d" % (width, height))
    if not os.path.exists(output_directory):
        os.makedirs(output_directory)
    os.chdir(output_directory)

    # Generate the individual frames.
    for hour in HOURS:
        html_path = os.path.join(HTML_DIRECTORY, hour, "index_2x.html")
        url = "file://%s" % (html_path, )
        subprocess.check_call(["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
                               "--headless",
                               "--screenshot=%s.png" % (hour, ),
                               "--window-size=%d,%d" % (width / 2, height / 2),
                               url])

    # Generate preview.
    with tempfile.TemporaryDirectory() as temporary_directory:
        slice_width = width / 12
        os.chdir(temporary_directory)
        for hour in HOURS:
            image_path = os.path.join(output_directory, "%s.png" % (hour, ))
            print(image_path)
            command = ["convert", image_path,
                       "+repage",
                       "-crop", "%dx%d+%d+0" % (slice_width, height, slice_width * int(hour) / 2),
                       "+repage",
                       "%s.png" % (hour, )]
            subprocess.check_call(command)
        slices = ["%s.png" % (hour, ) for hour in HOURS]
        command = ["convert"] + slices + ["+append", os.path.join(output_directory, "preview.png")]
        subprocess.check_call(command)


def main():
    parser = argparse.ArgumentParser()
    options = parser.parse_args()

    for (width, height) in DIMENSIONS:
        generate(width, height)


if __name__ == "__main__":
    main()
