#!/usr/bin/env python3

import os
import subprocess


SCRIPTS_DIRECTORY = os.path.dirname(os.path.abspath(__file__))
ROOT_DIRECTORY = os.path.dirname(SCRIPTS_DIRECTORY)
HTML_DIRECTORY = os.path.join(ROOT_DIRECTORY, "html")
RENDERS_DIRECTORY = os.path.join(ROOT_DIRECTORY, "renders")

HOURS = ["00", "02", "04", "06", "08", "10", "12", "14", "16", "18", "20", "22"]


def main():
    width = 3200
    height = 1333
    scale = 2

    output_directory = os.path.join(RENDERS_DIRECTORY, "%dx%d" % (width * scale, height * scale), "frames")
    os.makedirs(output_directory)
    os.chdir(output_directory)

    for hour in HOURS:
        html_path = os.path.join(HTML_DIRECTORY, hour, "index.html")
        url = "file://%s" % (html_path, )
        subprocess.check_call(["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
                               "--headless",
                               "--screenshot=%s.png" % (hour, ),
                               "--window-size=%s,%s" % (width, height),
                               url])


if __name__ == "__main__":
    main()
